# Objective:

The objective of this project is to analyze e-commerce sales data to uncover actionable insights into product performance, seasonal trends, customer behavior, and fulfillment strategies. By addressing key descriptive, inferential, and advanced analytical questions, the project aims to support businesses in:

Optimizing Product Performance:

- *Identifying top-performing and underperforming product categories and products.*
- *Understanding variations in sales, stock availability, and regional preferences.*

Leveraging Seasonal Trends:

- *Analyzing monthly, seasonal, and promotional sales patterns.*
- *Identifying peak sales periods and revenue fluctuations during holidays or events.*

Enhancing Customer Behavior Insights:

- *Examining customer purchasing patterns, including repeat purchases and return rates.*
- *Understanding regional shipping preferences and their impact on sales and satisfaction.*

Improving Fulfillment and Operational Efficiency:

- *Evaluating the effectiveness of shipping service levels and fulfillment methods.*
- *Exploring cost and time efficiencies in shipping and delivery processes.*

Supporting Strategic Decision-Making:

- *Providing data-driven recommendations for marketing strategies, inventory management, and operational improvements.*
- *Predicting key factors contributing to high-value orders and customer satisfaction.*

 Through comprehensive exploratory and statistical analysis, this project aims to deliver insights that empower businesses to enhance sales performance, optimize operations, and make informed strategic decisions.

In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Data Cleaning & Preprocessing

In [32]:
dataset = pd.read_csv('C:/Users/Elif Surucu/Documents/Flatiron/Assesments/Capstone/Analyzing_E_Commerce_SalesPerformance/Dataset/Dataset.csv')
print(dataset.head())

              Order_ID  Order_Date                  Order_Status  \
0  405-8078784-5731545  2022-04-30                     Cancelled
1  408-9553867-3715507  2022-04-27  Shipped - Delivered to Buyer
2  408-7468849-2134719  2022-04-24  Shipped - Delivered to Buyer
3  406-8338408-6778764  2022-04-20                     Cancelled
4  405-2959500-2916317  2022-04-19  Shipped - Delivered to Buyer

  Fulfilment_Method Sales_Channel Shipping_Service_Level Product_Style  \
0          Merchant     Amazon.in               Standard        SET389
1          Merchant     Amazon.in               Standard        SET389
2          Merchant     Amazon.in               Standard        SET389
3          Merchant     Amazon.in               Standard        SET389
4          Merchant     Amazon.in               Standard        SET389

      Product_SKU Product_Size Amazon_Standard_Identification_Number  ...  \
0  SET389-KR-NP-S            S                            B09KXVBD7Z  ...
1  SET389-KR-NP-S            S                            B09KXVBD7Z  ...
2  SET389-KR-NP-S            S                            B09KXVBD7Z  ...
3  SET389-KR-NP-S            S                            B09KXVBD7Z  ...
4  SET389-KR-NP-S            S                            B09KXVBD7Z  ...

         Customer_Name  Pieces    Rate  Gross_Amount   Index        SKU_Code  \
0  MULBERRIES BOUTIQUE     1.0  1000.0        1000.0  8978.0  SET389-KR-NP-S
1  MULBERRIES BOUTIQUE     1.0  1000.0        1000.0  8978.0  SET389-KR-NP-S
2  MULBERRIES BOUTIQUE     1.0  1000.0        1000.0  8978.0  SET389-KR-NP-S
3  MULBERRIES BOUTIQUE     1.0  1000.0        1000.0  8978.0  SET389-KR-NP-S
4  MULBERRIES BOUTIQUE     1.0  1000.0        1000.0  8978.0  SET389-KR-NP-S

   Design_Number Stock_Availability  Product_Color Product_Category
0         SET389               32.0          White              Set
1         SET389               32.0          White              Set
2         SET389               32.0          White              Set
3         SET389               32.0          White              Set
4         SET389               32.0          White              Set

[5 rows x 36 columns]

In [33]:
print(dataset.isnull().sum())

Order_ID                                      0
Order_Date                                    0
Order_Status                                  0
Fulfilment_Method                             0
Sales_Channel                                 0
Shipping_Service_Level                        0
Product_Style                                 0
Product_SKU                                   0
Product_Size                                  0
Amazon_Standard_Identification_Number         0
Courier_Status                                0
Quantity                                      0
Currency                                      0
Order_Amount                                  0
Shipping_City                                 0
Shipping_State                                0
Shipping_Postal_Code                          0
Shipping_Country                              0
Business_To_Business                          0
Fulfilled_By                             209586
Year                                          0
Month                                         0
Day                                           0
Day_of_Week                                   0
Transaction_Date                          57449
Transaction_Month                         57449
Customer_Name                             57449
Pieces                                    57449
Rate                                      57449
Gross_Amount                              57449
Index                                     22248
SKU_Code                                  22248
Design_Number                             22248
Stock_Availability                            0
Product_Color                                 0
Product_Category                              0
dtype: int64

In [34]:
dataset.drop(columns=['Fulfilled_By'], inplace=True)

In [35]:
dataset['Transaction_Date'] = pd.to_datetime(dataset['Transaction_Date'], format='%m-%d-%y', errors='coerce')
print(dataset['Transaction_Date'].head())
print(dataset['Transaction_Date'].info())

0   2022-01-29
1   2022-01-29
2   2022-01-29
3   2022-01-29
4   2022-01-29
Name: Transaction_Date, dtype: datetime64[ns]
<class 'pandas.core.series.Series'>
RangeIndex: 282039 entries, 0 to 282038
Series name: Transaction_Date
Non-Null Count   Dtype
--------------   -----
224590 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 2.2 MB
None

In [36]:
mode_date = dataset['Transaction_Date'].mode()[0]
dataset['Transaction_Date'].fillna(mode_date, inplace=True)
dataset['Year'] = dataset['Transaction_Date'].dt.year
dataset['Month'] = dataset['Transaction_Date'].dt.month
dataset['Day'] = dataset['Transaction_Date'].dt.day
dataset['Day_of_Week'] = dataset['Transaction_Date'].dt.dayofweek  # 0 = Monday, 6 = Sunday
dataset['Week_of_Year'] = dataset['Transaction_Date'].dt.isocalendar().week

In [37]:
print(dataset['Transaction_Date'].isnull().sum())

0

In [38]:
dataset.head()

,Order_ID,Order_Date,Order_Status,Fulfilment_Method,Sales_Channel,Shipping_Service_Level,Product_Style,Product_SKU,Product_Size,Amazon_Standard_Identification_Number,...,Pieces,Rate,Gross_Amount,Index,SKU_Code,Design_Number,Stock_Availability,Product_Color,Product_Category,Week_of_Year
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,S,B09KXVBD7Z,...,1.0,1000.0,1000.0,8978.0,SET389-KR-NP-S,SET389,32.0,White,Set,4
1,408-9553867-3715507,2022-04-27,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,S,B09KXVBD7Z,...,1.0,1000.0,1000.0,8978.0,SET389-KR-NP-S,SET389,32.0,White,Set,4
2,408-7468849-2134719,2022-04-24,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,S,B09KXVBD7Z,...,1.0,1000.0,1000.0,8978.0,SET389-KR-NP-S,SET389,32.0,White,Set,4
3,406-8338408-6778764,2022-04-20,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,S,B09KXVBD7Z,...,1.0,1000.0,1000.0,8978.0,SET389-KR-NP-S,SET389,32.0,White,Set,4
4,405-2959500-2916317,2022-04-19,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,S,B09KXVBD7Z,...,1.0,1000.0,1000.0,8978.0,SET389-KR-NP-S,SET389,32.0,White,Set,4

In [39]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282039 entries, 0 to 282038
Data columns (total 36 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Order_ID                               282039 non-null  object
 1   Order_Date                             282039 non-null  object
 2   Order_Status                           282039 non-null  object
 3   Fulfilment_Method                      282039 non-null  object
 4   Sales_Channel                          282039 non-null  object
 5   Shipping_Service_Level                 282039 non-null  object
 6   Product_Style                          282039 non-null  object
 7   Product_SKU                            282039 non-null  object
 8   Product_Size                           282039 non-null  object
 9   Amazon_Standard_Identification_Number  282039 non-null  object
 10  Courier_Status                         282039 non-null  object
 11  Quantity                               282039 non-null  float64
 12  Currency                               282039 non-null  object
 13  Order_Amount                           282039 non-null  float64
 14  Shipping_City                          282039 non-null  object
 15  Shipping_State                         282039 non-null  object
 16  Shipping_Postal_Code                   282039 non-null  float64
 17  Shipping_Country                       282039 non-null  object
 18  Business_To_Business                   282039 non-null  bool
 19  Year                                   282039 non-null  int32
 20  Month                                  282039 non-null  int32
 21  Day                                    282039 non-null  int32
 22  Day_of_Week                            282039 non-null  int32
 23  Transaction_Date                       282039 non-null  datetime64[ns]
 24  Transaction_Month                      224590 non-null  object
 25  Customer_Name                          224590 non-null  object
 26  Pieces                                 224590 non-null  float64
 27  Rate                                   224590 non-null  float64
 28  Gross_Amount                           224590 non-null  float64
 29  Index                                  259791 non-null  float64
 30  SKU_Code                               259791 non-null  object
 31  Design_Number                          259791 non-null  object
 32  Stock_Availability                     282039 non-null  float64
 33  Product_Color                          282039 non-null  object
 34  Product_Category                       282039 non-null  object
 35  Week_of_Year                           282039 non-null  UInt32
dtypes: UInt32(1), bool(1), datetime64[ns](1), float64(8), int32(4), object(21)
memory usage: 70.5+ MB

In [40]:
dataset.describe()

,Quantity,Order_Amount,Shipping_Postal_Code,Year,Month,Day,Day_of_Week,Transaction_Date,Pieces,Rate,Gross_Amount,Index,Stock_Availability,Week_of_Year
count,282039.000000,282039.000000,282039.000000,282039.000000,282039.000000,282039.000000,282039.000000,282039,224590.000000,224590.000000,224590.000000,259791.000000,282039.000000,282039.0
mean,0.907591,641.449845,464319.298838,2021.296470,6.941334,15.996887,2.218580,2021-10-31 08:50:02.750683392,1.377354,740.572712,980.639980,5337.408086,119.287432,28.420843
min,0.000000,0.000000,0.000000,2021.000000,1.000000,1.000000,0.000000,2021-06-05 00:00:00,1.000000,243.750000,232.000000,1.000000,0.000000,1.0
25%,1.000000,442.000000,382345.000000,2021.000000,3.000000,12.000000,1.000000,2021-09-14 00:00:00,1.000000,462.500000,524.000000,3595.500000,5.000000,12.0
50%,1.000000,635.000000,500034.000000,2021.000000,9.000000,14.000000,2.000000,2021-09-24 00:00:00,1.000000,681.000000,775.000000,5293.000000,28.000000,37.0
75%,1.000000,788.000000,600026.000000,2022.000000,9.000000,22.000000,4.000000,2022-01-29 00:00:00,1.000000,925.000000,1033.000000,8063.000000,152.000000,37.0
max,15.000000,5584.000000,989898.000000,2022.000000,12.000000,31.000000,6.000000,2022-03-31 00:00:00,15.000000,2087.500000,9735.000000,9230.000000,1234.000000,52.0
std,0.309992,267.285143,192153.567231,0.456701,3.364021,7.578073,1.660196,NaN,0.998793,318.523888,792.523994,2573.081372,197.895447,14.322487

# Descriptive Analysis Questions

**Product Categories**


1.	What percentage of total sales (Order_Amount) does each product category contribute?
2.	What is the average order amount (Order_Amount) for each product category?
3.	Which product category has the highest quantity sold?
4.	What is the distribution of Order_Amount within each product category?
5.	Which product categories have the highest stock availability (Stock_Availability)?
6.	How do product categories vary in terms of Rate per unit and Stock_Availability?
7.	Are there any product categories with consistently low sales?
8.	What are the top-selling products within each product category?
9.	How do high-selling products vary by region or season?


**Seasonal Trends**

10.	What are the monthly sales trends for the past year?
11.	Which months generate the highest and lowest revenue (Order_Amount)?
12.	What is the average order size (Quantity) by month?
13.	Which days of the week have the highest sales volume?
14.	What are the peak weeks (Week_of_Year) for sales in the dataset?
15.	Which months see the most significant increase in high-value orders (Order_Amount > 1000)?
16.	How does Order_Amount vary across seasons (e.g., winter, spring, summer, fall)?
17.	How does revenue differ between peak holiday weeks and non-peak weeks?



**Customer Behavior**

18.	What are the top 5 shipping destinations (Shipping_Country) by total sales?
19.	How does Courier_Status (e.g., on-time, delayed) impact Order_Status?
20.	What percentage of orders are fulfilled by different Fulfilment_Method options?
21.	What is the return rate (Order_Status = 'Returned') for orders across different product categories?
22.	What is the average delivery time for each shipping service level (Shipping_Service_Level)?
23.	How does Currency impact Order_Amount in different regions?
24.	What percentage of customers place repeat orders?
25.	How does the average Order_Amount differ between first-time and repeat customers?
26.	What is the average revenue contribution from high-value customers?


**Sales Channels and Fulfillment**

27.	What is the percentage split of sales between Sales_Channel (e.g., online, retail)?
28.	Which Shipping_Service_Level is most commonly used across high-value orders?
29.	How do Fulfilment_Method types vary across regions?
30.	What are the total shipping costs associated with different Shipping_City locations?

________________________________________
# Inferential Analysis Questions

1.	Are average sales (Order_Amount) significantly different between product categories?
- Example Test: One-way ANOVA or Kruskal-Wallis Test
2.	Does Quantity significantly impact Order_Amount across product categories?
- Example Test: Correlation or regression analysis
3.	Does Stock_Availability significantly impact Order_Amount for different product categories?
- Example Test: Regression Analysis
4.	Is the Rate per unit significantly different between top-selling categories?
- Example Test: T-test or Mann-Whitney U Test
Seasonal Trends
5.	Is there a significant difference in Order_Amount between peak holiday months (e.g., November-December) and the rest of the year?
- Example Test: T-test
6.	Does Day_of_Week significantly impact Order_Amount?
- Example Test: ANOVA or Kruskal-Wallis Test
7.	Are high-value orders (Order_Amount > 1000) more frequent in specific seasons or months?
- Example Test: Chi-square Test for Independence
Customer Behavior
8.	Do average order values (Order_Amount) differ between online and retail customers (Sales_Channel)?
- Example Test: T-test
9.	Is there a significant difference in delivery times for different Shipping_Service_Level options?
- Example Test: ANOVA
10.	Does Courier_Status (e.g., delayed vs. on-time) significantly affect Order_Amount?
- Example Test: T-test
11.	Are certain Shipping_Country locations associated with significantly higher sales?
- Example Test: Chi-square Test for Independence
Sales Channels and Fulfillment
12.	Is there a relationship between Fulfilment_Method and the likelihood of high-value orders?
- Example Test: Chi-square Test
13.	Do online orders have a significantly higher return rate than retail orders?
- Example Test: T-test
14.	Does the Sales_Channel significantly affect Order_Amount for specific product categories?
- Example Test: Two-way ANOVA
15.	Is Shipping_Service_Level a significant predictor of Order_Amount?
- Example Test: Regression Analysis
________________________________________
## Advanced and Combined Insights Questions
1.	What combination of Product_Category, Sales_Channel, and Shipping_Service_Level results in the highest Order_Amount?
2.	How does Stock_Availability influence Order_Status across different regions?
3.	How does seasonality affect customer preferences for shipping options?
4.	Do specific fulfillment methods see an increase during peak sales seasons?
5.	Which combination of Product_Category and Shipping_Country yields the highest average sales?
6.	How do Shipping_Service_Level and Courier_Status jointly impact delivery delays?
7.	Can Stock_Availability and Product_Size predict the likelihood of returns?
8.	Which combination of Shipping_Service_Level and Fulfilment_Method results in the fastest delivery times?
9.	Which factors (e.g., Stock_Availability, Product_Category, Shipping_Country) are the most significant predictors of high Order_Amount?
________________________________________
## Visual Analysis Questions
1.	How does the distribution of Order_Amount and high-value orders vary by Month, Product_Category, and region?
2.	Are certain Shipping_Countries associated with shorter delivery times?
3.	What is the relationship between Rate, Quantity, and Gross_Amount?
4.	Are orders with higher Stock_Availability associated with faster delivery times?
5.	How has sales performance changed year-over-year for top product categories?
6.	How do delivery times vary across Shipping_Countries, Fulfilment_Methods, and Stock_Availability by region?